#!/bin/bash

function HELP() {
cat <<EOF
Usage: $(basename "$0") [options] apk

options:
    cpd                    print apk copy instruction
    confusion              print apk confusion info
    apkdiff                print diff two apk file
    assetless              print unused asset file in apk directly
EOF
}

function warn() {
    [[ -n $1 ]] && echo $1
    exit 2
}

case $1 in
    assetless)
        shift && [ $# == 0 ] && warn "missing apk ..."
        . assets.sh $@ ;;
    rless)
        shift && [ $# == 0 ] && warn "missing apk ..."
        . arsc.sh $@ ;;
    apkdiff)
        shift && [ $# -lt 2 ] && warn "need two apk ..."
        . apkdiff.sh $@ ;;
    cpd)
        shift && [ $# == 0 ] && warn "missing apk ..."
        . common && apkdecode ${!#}
        [ ! -d $EXTRACT_DIR ] && warn "decode error ..."
        i=0
        for var in $@; do
            [[ $var = "-p" || $var = "--package" ]] && packagei="true"
            array[$i]=$var
            ((i++))
        done
        if [ -z $packagei ]; then
            apkpackageref $EXTRACT_DIR
            array[`expr $i - 1`]="-p"
            array[`expr $i`]=$APK_PACKAGE_REF
            array[`expr $i + 1`]=$EXTRACT_DIR
        else
            array[`expr $i - 1`]=$EXTRACT_DIR
        fi
        # echo ${array[@]}
        python3 cpd.py ${array[@]}
        ;;
    confusion)
        shift && . confusion.sh $@ ;;
    *)
        HELP ;;
esac