#!/bin/bash

function HELP() {
cat <<EOF
Usage: $(basename "$0") [options] apk

Options:
    cpd                         print apk copy instruction
    confusion                   print apk confusion info
    apkdiff [oldapk] [newapk]   print diff two apk file，oldapk newapk
    assetless                   print unused asset file in apk directly

cpd options:
    -h, --help                  show this help message and exit
    -t MINITOKENS, --minitokens=MINITOKENS
                                the lowest tokens, default: 100
    -p PACKAGE, --package=PACKAGE
                                specify the scan package name, '.' is all (default: application package name)

confusion options:
    -v --viz                    confusion scan result visualization 
    -p --package [package]      specify the scan package name, '.' is all (default: application package name)
EOF
}

function warn() {
    [[ -n $1 ]] && echo $1
    exit 2
}

case $1 in
    assetless)
        shift && [ $# == 0 ] && warn "missing apk ..."
        . assets.sh $@ ;;
    rless)
        shift && [ $# == 0 ] && warn "missing apk ..."
        . arsc.sh $@ ;;
    apkdiff)
        shift && [ $# -lt 2 ] && warn "need two apk ..."
        . apkdiff.sh $@ ;;
    cpd)
        shift && [ $# == 0 ] && python3 cpd.py && warn ""
        . common && apkdecode ${!#}
        [ ! -d $EXTRACT_DIR ] && warn "decode error ..."
        i=0
        for var in $@; do
            [[ $var = "-p" || $var = "--package" ]] && packagei="true"
            array[$i]=$var
            ((i++))
        done
        if [ -z $packagei ]; then
            apkpackageref $EXTRACT_DIR
            array[`expr $i - 1`]="-p"
            array[`expr $i`]=$APK_PACKAGE_REF
            array[`expr $i + 1`]=$EXTRACT_DIR
        else
            array[`expr $i - 1`]=$EXTRACT_DIR
        fi
        # echo ${array[@]}
        python3 cpd.py ${array[@]}
        ;;
    confusion)
        shift && . confusion.sh $@ ;;
    *)
        HELP ;;
esac